### ISSUE TITLE
NODEJSVOIP does not work on Mozilla firefox

### ISSUE THREAD

**Issue by ghost** [cracker0dks/nodeJsVoip#1]
the recording is cut after five seconds on mozilla ?

**Comment by ghost** [comment]
ok i am fixed bug

**Comment by cracker0dks** [comment]
this bug was in your system? or do I have to fix it in my code ?

**Comment by ghost** [comment]
I would like to work with you to a big project, you have  email ?

**Comment by cracker0dks** [comment]
yeah sure... i'd like to hear your ideas: emailRemoved

**Comment by blackofuil** [comment]
thank
