### ISSUE TITLE
Implementing such solution in Android or iOS

### ISSUE THREAD

**Issue by NasserAlmanji** [cracker0dks/nodeJsVoip#2]
Hi,

Just tested the server you created and it works. 

I have a question, how easy is it to migrate the same solution (web browser client) to a mobile based client on iOS or Android?

The server will stay the same,

Nasser

**Comment by NasserAlmanji** [comment]
In mobile browsers, it works on Android system but not the iOS. This might goes back to the fact that Android system supports worker processes in browsers (push notifications work too in Android browsers).

**Comment by cracker0dks** [comment]
Can not test on iOS, but WebWorkers should be rdy at iOS 8.1 and above: https://software.intel.com/en-us/forums/intel-xdk/topic/612990

So I cant really help you here sry.

**Comment by NasserAlmanji** [comment]
Ok, thanks for your help

Sent from my iPhone

On Apr 8, 2018, at 5:24 PM, Cracker <notifications@github.com<mailto:notifications@github.com>> wrote:


Can not test on iOS, but WebWorkers should be rdy at iOS 8.1 and above: https://software.intel.com/en-us/forums/intel-xdk/topic/612990

So I cant really help you here sry.
