### ISSUE TITLE
Speakers

### ISSUE THREAD

**Issue by ibanzai** [cracker0dks/nodeJsVoip#4]
How do I play the data received from the server through the speakers?

**Comment by cracker0dks** [comment]
hey, I updated some code libs and added a "start" button. If you open two tabs and click on start in both you should hear yourself

**Comment by ibanzai** [comment]
Indeed, thank you for the update! Do you have any thoughts about preventing echo between the mic and speaker?

**Comment by cracker0dks** [comment]
no, no further dev plans. If you want a "real" voicechat please consider to use webrtc. Take a look here: https://github.com/feross/simple-peer
for peer2peer or at other sfu/mcu projects
